services:
  fintech: &fintech
    build:
      context: .
      dockerfile: ./docker/local/django/Dockerfile
    volumes:
      - .:/app:z
      - staticfiles_volume:/app/staticfiles
#    ports:
#      - "8000:8000"
    expose:
      - "8000"
    env_file:
      - ./fintech/.envs/.env.local
    depends_on:
      - postgres
      - mailpit
      - redis
      - rabbitmq
    command: /start.sh
    networks:
      - fintech_bank

  postgres:
    build:
      context: .
      dockerfile: ./docker/local/postgres/Dockerfile
    ports:
      - "5433:5433"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./fintech/.envs/.env.local
    networks:
      - fintech_bank

  mailpit:
    image: docker.io/axllent/mailpit:v1.20.3
    ports:
      - "8025:8025"
    volumes:
      - mailpit_data:/data
    environment:
      MP_MAX_MESSAGES: 500
      MP_DATA_FILE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
    networks:
      - fintech_bank

  nginx:
    build:
      context: ./docker/local/nginx
      dockerfile: Dockerfile
    restart: always
    ports:
      - "9090:80"
    volumes:
      - staticfiles_volume:/app/staticfiles
      - logs_store:/var/log/nginx
    depends_on:
      - fintech
    networks:
      - fintech_bank
  redis:
    image: redis:7.0-alpine3.19
    command: redis-server --appendonly yes
    networks:
      - fintech_bank

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5682:5682"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - rabbitmq_log:/var/log/rabbitmq
    networks:
      - fintech_bank
  celeryworker:
    <<: *fintech
    command: /start-celeryworker.sh

  flower:
    <<: *fintech
    ports:
      - "5555:5555"
    volumes:
      - flower_db:/app/flower_db
    command: /start-flower.sh

  celerybeat:
    build:
      context: .
      dockerfile: ./docker/local/django/Dockerfile
    command: /start-celerybeat.sh
    env_file:
      - ./fintech/.envs/.env.local
    depends_on:
      - redis
      - postgres
      - rabbitmq
    networks:
      - fintech_bank


networks:
  fintech_bank:
    name: fintech_bank
    external: true

volumes:
  postgres_data:
  mailpit_data:
  logs_store:
  rabbitmq_data:
  rabbitmq_log:
  flower_db:
  staticfiles_volume:
